### ISSUE TITLE
Invisible ball in Linux

### ISSUE THREAD

**Issue by JanPoonthong** [tsoding/metaballs#2]
**Describe the bug**
I can't see the balls in Linux. Mouse and keyboard "q" key work, but the ball is nowhere to be seen.

**To Reproduce**
I followed the instruction on README.md.

```console
$ make
$ ./metaballs
```

**Expected behavior**
I expected to run the `./metaballs` and use my mouse the move around the ball, but the balls are nowhere to be seen. I will provide a link to a video you can see it there.

Link to video of metaballs -> https://streamable.com/5q0ey8 

**Environment**

- metaballs on commit #5a8e56c6312a98e4892676c53047d32f758cf420
- OS: Linux mint 20.1 based on Ubuntu
- Terminal: GNOME Terminal
- gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Additional context**
I don't what I'm missing or what key should I hit, but I think I don't have to after watching your stream. I saw just a ball appear on the screen, mine doesn't.

**Comment by rexim** [comment]
Have you tried clang?

**Comment by JanPoonthong** [comment]
Clang works, thanks @rexim
